export const colors = {
  paper: '#FBFAF6',
  surface: '#FFFFFF',
  ink: '#20291F',
  inkSoft: '#6B7669',
  line: '#E1DACB',
  green: '#3F6B4A',
  greenSoft: '#E4EDE2',
  amber: '#A9691A',
  amberSoft: '#F5E7CE',
  red: '#A23A2E',
  redSoft: '#F3DBD6',

  // Palette "dispensa illustrata": accenti vivaci ispirati alla grafica di riferimento
  teal: '#2FA79B',
  tealDark: '#1F7F76',
  tealSoft: '#DBF0EC',
  cream: '#FBF1DE',
  gold: '#F5C463',
  wood: '#E8B98A',
  pillGreen: '#2E9767',
  pillGreenSoft: '#DFF3E8',
  pillRed: '#E1574C',
  pillRedSoft: '#FBE0DD',
  pillBlue: '#2E76B4',
  pillBlueSoft: '#DDEAF6',
  pillAmber: '#C97A2B',
  pillAmberSoft: '#F6E4D0',
  berry: '#B23A63',
  berryDark: '#8C2A4C',
  berrySoft: '#F5DDE6',
  amberDark: '#A15F1C',
};

export const fonts = {
  displaySemiBold: 'Archivo_600SemiBold',
  displayBold: 'Archivo_700Bold',
  displayExtraBold: 'Archivo_800ExtraBold',
  displayBlack: 'Archivo_900Black',
  body: 'WorkSans_400Regular',
  bodyMedium: 'WorkSans_500Medium',
  bodySemiBold: 'WorkSans_600SemiBold',
  bodyBold: 'WorkSans_700Bold',
};
